[build]
  base    = "real-estate-dashboard"
  install = "npm install --legacy-peer-deps"
  command = "CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
