services:
  - type: web
    name: demo-entorach-site-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: demo-entorach-site-db
          property: connectionString
    plan: free
    numInstances: 1
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: demo-entorach-site-db
    databaseName: demo_entorach_site_db
    user: demo_entorach_site_user
    plan: free
